TH5/TH5/Controllers/CanHoController.cs
using Microsoft.AspNetCore.Mvc;
using TH5.Models;

namespace TH5.Controllers
{
    public class CanHoController:Controller
    {
        public IActionResult ThemCanHo()
        {
            return View();
        }

        [HttpPost]
        public string AddCH(CanHoModel canho)
        {
            int count;
            DataContext context = HttpContext.RequestServices.GetService(typeof(TH5.Models.DataContext)) as DataContext;
            count = context.Create(canho);
            if(count == 1)
            {
                return "Thêm Thành Công!";
            }
            return "Thêm thất bại";
        }
    }
}

TH5/TH5/Controllers/NhanVienController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TH5.Models;

namespace TH5.Controllers
{
    public class NhanVienController : Controller
    {

        public IActionResult Index()
        {
            DataContext context = HttpContext.RequestServices.GetService(typeof(TH5.Models.DataContext)) as DataContext;
            return View(context.getTenNhanVien());
        }

        public IActionResult ListTB(string id)
        {
            DataContext context = HttpContext.RequestServices.GetService(typeof(TH5.Models.DataContext)) as DataContext;
            return View(context.getListTB(id));
        }

        public IActionResult Edit(string id, string id1, string id2, int id3)
        {
            DataContext context = HttpContext.RequestServices.GetService(typeof(TH5.Models.DataContext)) as DataContext;
            ViewData["NV_BT"] = context.getNVBT(id, id1, id2, id3);
            return View(context.getNVBT(id, id1, id2, id3));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(string id, string id1, string id2, int id3, NV_BT nv)
        {

            DataContext context = HttpContext.RequestServices.GetService(typeof(TH5.Models.DataContext)) as DataContext;
            if (context.Update(nv) != 0)
            {
                return Redirect("/NhanVien/ListTB?id=" + nv.MaNhanVien);
            }
            return Redirect("/NhanVien/ListTB?id=" + nv.MaNhanVien);
        }

        public IActionResult Delete(string id, string id1, string id2, int id3)
        {
            DataContext context = HttpContext.RequestServices.GetService(typeof(TH5.Models.DataContext)) as DataContext;
            if (context.Delete(id, id1, id2, id3) != 0)
            {
                return Redirect("/NhanVien/ListTB?id=" + id);
            }
            return Redirect("/NhanVien/ListTB?id=" + id);
        }

        public IActionResult Search(int id)
        {
            DataContext context = HttpContext.RequestServices.GetService(typeof(TH5.Models.DataContext)) as DataContext;
            return View(context.getNhanVien(id));
        }
    }
}

TH5/TH5/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - QUANLYBAOTRITHIETBI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">QUANLYBAOTRITHIETBI</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CanHo" asp-action="ThemCanHo">Câu 1. Thêm Căn Hộ</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="NhanVien" asp-action="Search">Câu 2. Liệt kê nhân viên theo lần</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="NhanVien" asp-action="Index">Câu 3. List Nhan Vien</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - QUANLYBAOTRITHIETBI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>